[tool.ruff]
# General settings for Ruff
line-length = 88
target-version = "py311"

[tool.ruff.lint]
# Enable specific rule sets by their code
select = ["E", "F", "I", "ERA001"]
ignore = ["E501"]

[tool.ruff.format]
# Formatting style settings
quote-style = "double"
docstring-code-format = true

